name: run pull request CI

on:
  schedule:
    - cron:  '0 12 * * *'  # daily ~8am est
  workflow_dispatch:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]
        command: ["py", "scaffolds"]

    steps:
      - uses: actions/checkout@v2
      - name: setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: install tox
        run: pip install tox
      - name: run tox unit tests
        run: tox -e ${{ matrix.command }}
